# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# https://alacritty.org/config-alacritty.html

# Font configuration
[font]
size = 12.5

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"
