# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"
